### ISSUE TITLE
Adding helpful resources for each segements

### ISSUE THREAD

**Issue by dee-d-dev** [sharonikechi/technical-framework#1]
I am a Junior Backend Engineer striving to grow everyday and this resource has been so helpful on what to do next or what to improve on but I feel having helpful resources attached to them would be great as well; At least resources that have been helpful to the maintainers e.g Books, research papers, link to videos e.t.c

Thanks

**Comment by BolajiOlajide** [comment]
Thank you so much for your contribution.
Apologies it took some time to get into it.
